google_domain = {
    "Samoa": "google.ws",
    "Vanuatu": "google.vu",
    "British Virgin Islands": "google.vg",
    "Trinidad and Tobago": "google.tt",
    "Tonga": "google.to",
    "Tunisia": "google.tn",
    "Turkmenistan": "google.tm",
    "Timor-Leste": "google.tl",
    "Tokelau": "google.tk",
    "Togo": "google.tg",
    "Chad": "google.td",
    "São Tomé and Príncipe": "google.st",
    "Suriname": "google.sr",
    "Somalia": "google.so",
    "Senegal": "google.sn",
    "San Marino": "google.sm",
    "Slovakia": "google.sk",
    "Slovenia": "google.si",
    "Saint Helena, Ascension and Tristan da Cunha": "google.sh",
    "Sweden": "google.se",
    "Seychelles": "google.sc",
    "Rwanda": "google.rw",
    "Russia": "google.ru",
    "Serbia": "google.rs",
    "Romania": "google.ro",
    "Portugal": "google.pt",
    "Palestine[3]": "google.ps",
    "Poland": "google.pl",
    "Niue": "google.nu",
    "Nauru": "google.nr",
    "Norway": "google.no",
    "Netherlands": "google.nl",
    "Niger": "google.ne",
    "Malawi": "google.mw",
    "Maldives": "google.mv",
    "Mauritius": "google.mu",
    "Montserrat": "google.ms",
    "Mongolia": "google.mn",
    "Mali": "google.ml",
    "Macedonia": "google.mk",
    "Madagascar": "google.mg",
    "Montenegro": "google.me",
    "Moldova": "google.md",
    "Latvia": "google.lv",
    "Luxembourg": "google.lu",
    "Lithuania": "google.lt",
    "Sri Lanka": "google.lk",
    "Liechtenstein": "google.li",
    "Laos": "google.la",
    "Kazakhstan": "google.kz",
    "Kiribati": "google.ki",
    "Kyrgyzstan": "google.kg",
    "Jordan": "google.jo",
    "Jersey": "google.je",
    "Italy": "google.it",
    "Iceland": "google.is",
    "Iraq": "google.iq",
    "British Indian Ocean Territory": "google.io",
    "Isle of Man": "google.im",
    "Ireland": "google.ie",
    "Hungary": "google.hu",
    "Haiti": "google.ht",
    "Croatia": "google.hr",
    "Honduras": "google.hn",
    "Guyana": "google.gy",
    "Greece": "google.gr",
    "Guadeloupe": "google.gp",
    "Gambia": "google.gm",
    "Greenland": "google.gl",
    "Guernsey": "google.gg",
    "French Guiana": "google.gf",
    "Georgia": "google.ge",
    "Gabon": "google.ga",
    "France": "google.fr",
    "Federated States of Micronesia": "google.fm",
    "Finland": "google.fi",
    "Spain": "google.es",
    "Estonia": "google.ee",
    "Algeria": "google.dz",
    "Dominica": "google.dm",
    "Denmark": "google.dk",
    "Djibouti": "google.dj",
    "Germany": "google.de",
    "Czech Republic": "google.cz",
    "Cape Verde": "google.cv",
    "Vietnam": "google.com.vn",
    "Saint Vincent and the Grenadines": "google.com.vc",
    "Uruguay": "google.com.uy",
    "Ukraine": "google.com.ua",
    "Taiwan": "google.com.tw",
    "Turkey": "google.com.tr",
    "Tajikistan": "google.com.tj",
    "El Salvador": "google.com.sv",
    "Sierra Leone": "google.com.sl",
    "Singapore": "google.com.sg",
    "Solomon Islands": "google.com.sb",
    "Saudi Arabia": "google.com.sa",
    "Qatar": "google.com.qa",
    "Paraguay": "google.com.py",
    "Puerto Rico": "google.com.pr",
    "Pakistan": "google.com.pk",
    "Philippines": "google.com.ph",
    "Papua New Guinea": "google.com.pg",
    "Peru": "google.com.pe",
    "Panama": "google.com.pa",
    "Oman": "google.com.om",
    "Nepal": "google.com.np",
    "Nicaragua": "google.com.ni",
    "Nigeria": "google.com.ng",
    "Norfolk Island": "google.com.nf",
    "Namibia": "google.com.na",
    "Malaysia": "google.com.my",
    "Mexico": "google.com.mx",
    "Malta": "google.com.mt",
    "Myanmar": "google.com.mm",
    "Libya": "google.com.ly",
    "Saint Lucia": "google.com.lc",
    "Lebanon": "google.com.lb",
    "Kuwait": "google.com.kw",
    "Cambodia": "google.com.kh",
    "Jamaica": "google.com.jm",
    "Hong Kong": "google.com.hk",
    "Guatemala": "google.com.gt",
    "Gibraltar": "google.com.gi",
    "Ghana": "google.com.gh",
    "Fiji": "google.com.fj",
    "Ethiopia": "google.com.et",
    "Egypt": "google.com.eg",
    "Ecuador": "google.com.ec",
    "Dominican Republic": "google.com.do",
    "Cyprus": "google.com.cy",
    "Cuba": "google.com.cu",
    "Colombia": "google.com.co",
    "Belize": "google.com.bz",
    "Brazil": "google.com.br",
    "Bolivia": "google.com.bo",
    "Brunei": "google.com.bn",
    "Bahrain": "google.com.bh",
    "Bangladesh": "google.com.bd",
    "Australia": "google.com.au",
    "Argentina": "google.com.ar",
    "Anguilla": "google.com.ai",
    "Antigua and Barbuda": "google.com.ag",
    "Afghanistan": "google.com.af",
    "Worldwide (Original for the United States)": "google.com",
    "United States": "google.com",
    "Zimbabwe": "google.co.zw",
    "Zambia": "google.co.zm",
    "South Africa": "google.co.za",
    "United States Virgin Islands": "google.co.vi",
    "Venezuela": "google.co.ve",
    "Uzbekistan": "google.co.uz",
    "United Kingdom": "google.co.uk",
    "Uganda": "google.co.ug",
    "Tanzania": "google.co.tz",
    "Thailand": "google.co.th",
    "Pitcairn Islands": "google.co.pn",
    "New Zealand": "google.co.nz",
    "Mozambique": "google.co.mz",
    "Morocco": "google.co.ma",
    "Lesotho": "google.co.ls",
    "South Korea": "google.co.kr",
    "Kenya": "google.co.ke",
    "Japan": "google.co.jp",
    "India": "google.co.in",
    "Israel": "google.co.il",
    "Indonesia": "google.co.id",
    "Costa Rica": "google.co.cr",
    "Cook Islands": "google.co.ck",
    "Botswana": "google.co.bw",
    "Angola": "google.co.ao",
    "Cameroon": "google.cm",
    "Chile": "google.cl",
    "Ivory Coast": "google.ci",
    "Switzerland": "google.ch",
    "Republic of the Congo": "google.cg",
    "Central African Republic": "google.cf",
    "Democratic Republic of the Congo": "google.cd",
    "Cocos (Keeling) Islands": "google.cc",
    "Catalan Countries": "google.cat",
    "Canada": "google.ca",
    "Belarus": "google.by",
    "Bhutan": "google.bt",
    "Bahamas": "google.bs",
    "Benin": "google.bj",
    "Burundi": "google.bi",
    "Bulgaria": "google.bg",
    "Burkina Faso": "google.bf",
    "Belgium": "google.be",
    "Bosnia and Herzegovina": "google.ba",
    "Azerbaijan": "google.az",
    "Austria": "google.at",
    "American Samoa": "google.as",
    "Armenia": "google.am",
    "Albania": "google.al",
    "United Arab Emirates": "google.ae",
    "Andorra": "google.ad",
    "Ascension Island": "google.ac",
    "China": "g.cn",
}