name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - '**/MANIFEST.in'
      - '**/LICENSE'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - '**/MANIFEST.in'
      - '**/LICENSE'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run tests and collect coverage
        run: |
          poetry run python -m pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}